### ISSUE TITLE
[iOS] Banner (bottom) overlaps Ionic 3 bottom tab bar

### ISSUE THREAD

**Issue by svzi** [admob-plus/admob-plus#26]
Title says it all. As soon as the banner is loaded / displayed on iOS, it overlays my bottom tab bar. So the navigation is unavailable, as soon as the banner shows. This doesn't happen on Android.

I did not experience this issue with `cordova-plugin-admob-free`. I've also noticed that the old plugin had the configuration property `overlap: boolean`(see https://ratson.github.io/cordova-plugin-admob-free/typedef/index.html#static-typedef-BannerConfig) which seems to be missing in `admob-plus`. 

Maybe there is another way to avoid the overlapping on iOS and I'm just missing it. 

@ratson @ratson0  Do I need to switch back to the old plugin to get it working again?

**Comment by svzi** [comment]
@ratson @ratson0 I would really appreciate any kind of feedback or support.

**Comment by svzi** [comment]
I feel lost with my issues.

**Comment by svzi** [comment]
@ratson @ratson0 Don't get me wrong, but as far as I know you're looking for some funding on this project, which I can truly understand. I would love to support you, but I need to get it working before. And, to be honest, I would expect some kind of support, without the need to wait 17 days and push this thread multiple times. 

I would understand the missing support if you were on some kind of vacation or otherwise busy, but the commit history in this repository shows that you're constantly working on this project (which is great to be clear!)... You're just ignoring some issues, which makes me feel sad and lost.

j2mc!

**Comment by svzi** [comment]
*ping*

**Comment by ratson** [comment]
@svzi Sorry for that you feel lost with your issue. I develop this project in my limited spare time, and it is time consuming to reproduce issues, especially for those without much details. That's why I recently added issues template and [a cli tool](https://github.com/admob-plus/admob-plus/tree/master/packages/cli) to help addressing that.
(btw, I always look into bug report with reproducible repo, but it is just that rarely people are doing so to save maintainer's time)

Did you try the latest version? I think the issue is fixed in v0.12.0.

**Comment by svzi** [comment]
@ratson Thanks for getting back to me, I really appreciate that. I also understand how hard it is, to reproduce issues without much details. That's why I tried to point out the differences to your other, older, plugin. I thought it was clear from the beginning, but I could also supply a repo to reproduce the issue.

But first of all I will try the current version (0.12.0+). I will let you know if it works. If it doesn't work, I will provide a repo with the issue.

**Comment by svzi** [comment]
Showing the banner finally doesn't overlap the content anymore (tested with version 0.15.0)! 👍 

But when I hide the banner, the bottom bar where the banner was shown is still there. Just the banner is going away, but the screen space is missing. When I show an Interstitial then, close it and display the banner again, the banner is overlapping the content (my bottom tab bar) again. So it looks like something with hiding the banner doesn't work as expected.

**Comment by nathantaal** [comment]
@svzi Could you maybe close the issue since it's resolved?

**Comment by svzi** [comment]
@nathantaal Did you read my last comment completely? The problem is not completely solved. So I hesitate to close this ticket.

**Comment by svzi** [comment]
It's working with the latest version!

**Comment by bhar4t** [comment]
How can I overlay/overlap banner in app? I didn't see any configuration in docs, Please help.
