### ISSUE TITLE
Interstitial, app open & reward ads are not working

### ISSUE THREAD

**Issue by merbin2012** [admob-plus/admob-plus#585]
Sorry for disturbing again, currently I have read all your documents and implemented them. The banner ads are perfect working  also the load events are working, 

![screenshot-nimbusweb me-2023 06 10-20_45_19](https://github.com/admob-plus/admob-plus/assets/3687184/788c59e5-e5fe-4fa9-b994-ceae6ad3aab1)

But after that, when I tried to show the interstitial or app Open or reward ads the app crashed with the following information.

![1686409895845](https://github.com/admob-plus/admob-plus/assets/3687184/23cb398a-c332-48b6-9aca-b075a4af35ea)

**When this error occurs the Android studio logs are given below**

**Logs in image**
![image](https://github.com/admob-plus/admob-plus/assets/3687184/2d404df1-a0c4-484d-94c5-8b5bc6540d5c)

**Logs in Text**
`2023-06-10 20:53:20.204 22194-4402  AudioTrack              maths.formulas                       D  [audioTrackData][fine] 20s(f:20031 m:977 s:0 k:0) : pid 22194 uid 10710 sessionId 17361 sr 44100 ch 2 fmt 1
2023-06-10 20:53:21.097 22194-22194 CordovaActivity         maths.formulas                       D  Paused the activity.
2023-06-10 20:53:21.097 22194-22194 AndroidRuntime          maths.formulas                       D  Shutting down VM
2023-06-10 20:53:21.098 22194-22194 AndroidRuntime          maths.formulas                       E  FATAL EXCEPTION: main
                                                                                                    Process: maths.formulas, PID: 22194
                                                                                                    java.lang.RuntimeException: Unable to pause activity {maths.formulas/maths.formulas.MainActivity}: java.lang.ClassCastException: java.util.LinkedHashMap$LinkedHashMapEntry cannot be cast to admob.plus.cordova.ads.AdBase
                                                                                                    	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5263)
                                                                                                    	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5214)
                                                                                                    	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5166)
                                                                                                    	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8261)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                                                                                    Caused by: java.lang.ClassCastException: java.util.LinkedHashMap$LinkedHashMapEntry cannot be cast to admob.plus.cordova.ads.AdBase
                                                                                                    	at admob.plus.cordova.AdMob.onPause(AdMob.kt:247)
                                                                                                    	at org.apache.cordova.PluginManager.onPause(PluginManager.java:241)
                                                                                                    	at org.apache.cordova.CordovaWebViewImpl.handlePause(CordovaWebViewImpl.java:482)
                                                                                                    	at org.apache.cordova.CordovaActivity.onPause(CordovaActivity.java:255)
                                                                                                    	at android.app.Activity.performPause(Activity.java:8719)
                                                                                                    	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1619)
                                                                                                    	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5253)
                                                                                                    	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5214) 
                                                                                                    	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5166) 
                                                                                                    	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47) 
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8261) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
2023-06-10 20:53:21.093 22194-22194 maths.formulas          maths.formulas                       W  type=1400 audit(0.0:300305): avc: denied { search } for name="miuilog" dev="dm-54" ino=388988 scontext=u:r:untrusted_app:s0:c198,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=maths.formulas
2023-06-10 20:53:21.093 22194-22194 maths.formulas          maths.formulas                       W  type=1400 audit(0.0:300306): avc: denied { search } for name="miuilog" dev="dm-54" ino=388988 scontext=u:r:untrusted_app:s0:c198,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=maths.formulas
2023-06-10 20:53:21.093 22194-22194 maths.formulas          maths.formulas                       W  type=1400 audit(0.0:300307): avc: denied { search } for name="miuilog" dev="dm-54" ino=388988 scontext=u:r:untrusted_app:s0:c198,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=maths.formulas
2023-06-10 20:53:21.093 22194-22194 maths.formulas          maths.formulas                       W  type=1400 audit(0.0:300308): avc: denied { search } for name="miuilog" dev="dm-54" ino=388988 scontext=u:r:untrusted_app:s0:c198,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=maths.formulas
2023-06-10 20:53:21.093 22194-22194 maths.formulas          maths.formulas                       W  type=1400 audit(0.0:300309): avc: denied { search } for name="miuilog" dev="dm-54" ino=388988 scontext=u:r:untrusted_app:s0:c198,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=maths.formulas
2023-06-10 20:53:21.099 22194-22194 OOMEventManagerFK       maths.formulas                       W  Failed to mkdir /data/miuilog/stability/memleak/heapdump/
2023-06-10 20:53:21.093 22194-22194 maths.formulas          maths.formulas                       W  type=1400 audit(0.0:300310): avc: denied { search } for name="miuilog" dev="dm-54" ino=388988 scontext=u:r:untrusted_app:s0:c198,c258,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=maths.formulas
2023-06-10 20:53:21.099 22194-4296  FA                      maths.formulas                       E  Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
2023-06-10 20:53:21.102 22194-22194 maths.formulas          maths.formulas                       W  Attempt to remove non-JNI local reference, dumping thread
2023-06-10 20:53:21.105 22194-22194 Process                 maths.formulas                       I  Process is going to kill itself!
                                                                                                    java.lang.Exception
                                                                                                    	at android.os.Process.killProcess(Process.java:1344)
                                                                                                    	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
                                                                                                    	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle6432.aab-stable-573506133:17)
                                                                                                    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
                                                                                                    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                                                    	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
2023-06-10 20:53:21.105 22194-22194 Process                 maths.formulas                       I  Sending signal. PID: 22194 SIG: 9
---------------------------- PROCESS ENDED (22194) for package maths.formulas ----------------------------
---------------------------- PROCESS STARTED (22195) for package maths.formulas ----------------------------
2023-06-10 20:53:21.269 22195-22195 Compatibil...geReporter maths.formulas                       D  Compat change id reported: 171979766; UID 10710; state: ENABLED
2023-06-10 20:53:21.271 22195-4569  AppScoutStateMachine    maths.formulas                       D  22195-ScoutStateMachinecreated
2023-06-10 20:53:21.274 22195-22195 ziparchive              maths.formulas                       W  Unable to open '/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.dm': No such file or directory
2023-06-10 20:53:21.274 22195-22195 ziparchive              maths.formulas                       W  Unable to open '/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.dm': No such file or directory
2023-06-10 20:53:21.374 22195-22195 nativeloader            maths.formulas                       D  Configuring classloader-namespace for other apk /data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/maths.formulas
2023-06-10 20:53:21.380 22195-22195 Perf                    maths.formulas                       I  Connecting to perf service.
2023-06-10 20:53:21.383 22195-22195 GraphicsEnvironment     maths.formulas                       V  ANGLE Developer option for 'maths.formulas' set to: 'default'
2023-06-10 20:53:21.383 22195-22195 GraphicsEnvironment     maths.formulas                       V  ANGLE GameManagerService for maths.formulas: false
2023-06-10 20:53:21.383 22195-22195 GraphicsEnvironment     maths.formulas                       V  Updatable production driver is not supported on the device.
2023-06-10 20:53:21.386 22195-22195 ForceDarkHelperStubImpl maths.formulas                       I  initialize for maths.formulas , ForceDarkAppConfig: null
2023-06-10 20:53:21.387 22195-22195 maths.formulas          maths.formulas                       D  JNI_OnLoad success
2023-06-10 20:53:21.387 22195-22195 MiuiForceDarkConfig     maths.formulas                       I  setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
2023-06-10 20:53:21.388 22195-22195 NetworkSecurityConfig   maths.formulas                       D  No Network Security Config specified, using platform default
2023-06-10 20:53:21.389 22195-22195 NetworkSecurityConfig   maths.formulas                       D  No Network Security Config specified, using platform default
2023-06-10 20:53:21.392 22195-22195 WM-WrkMgrInitializer    maths.formulas                       D  Initializing WorkManager with default configuration.
2023-06-10 20:53:21.408 22195-22195 MiuiMultiWindowAdapter  maths.formulas                       D  MiuiMultiWindowAdapter::getFreeformVideoWhiteListInSystem::LIST_ABOUT_SUPPORT_LANDSCAPE_VIDEO = [com.hunantv.imgo.activity, com.tencent.qqlive, com.qiyi.video, com.hunantv.imgo.activity.inter, com.tencent.qqlivei18n, com.iqiyi.i18n, tv.danmaku.bili]
2023-06-10 20:53:21.416 22195-4580  Compatibil...geReporter maths.formulas                       D  Compat change id reported: 160794467; UID 10710; state: ENABLED
2023-06-10 20:53:21.418 22195-22195 libc                    maths.formulas                       W  Access denied finding property "ro.vendor.df.effect.conflict"
2023-06-10 20:53:21.444 22195-22195 nativeloader            maths.formulas                       D  Configuring classloader-namespace for other apk /system/framework/org.apache.http.legacy.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/lib/arm64:/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
2023-06-10 20:53:21.444 22195-22195 nativeloader            maths.formulas                       D  Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libmisys_jni.xiaomi.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
2023-06-10 20:53:21.448 22195-22195 nativeloader            maths.formulas                       D  Configuring classloader-namespace for other apk /system/framework/com.android.media.remotedisplay.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/lib/arm64:/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
2023-06-10 20:53:21.448 22195-22195 nativeloader            maths.formulas                       D  Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libmisys_jni.xiaomi.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
2023-06-10 20:53:21.450 22195-22195 maths.formulas          maths.formulas                       W  Loading /data/misc/apexdata/com.android.art/dalvik-cache/arm64/system@framework@com.android.location.provider.jar@classes.odex non-executable as it requires an image which we failed to load
2023-06-10 20:53:21.450 22195-22195 nativeloader            maths.formulas                       D  Configuring classloader-namespace for other apk /system/framework/com.android.location.provider.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/lib/arm64:/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
2023-06-10 20:53:21.450 22195-22195 nativeloader            maths.formulas                       D  Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libQOC.qti.so:libmisys_jni.xiaomi.so:libupdateprof.qti.so:libthermalclient.qti.so:libQOC.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
2023-06-10 20:53:21.453 22195-22195 nativeloader            maths.formulas                       D  Configuring classloader-namespace for other apk /data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/lib/arm64:/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
2023-06-10 20:53:21.484 22195-22195 DynamiteModule          maths.formulas                       I  Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:231710100
2023-06-10 20:53:21.484 22195-22195 DynamiteModule          maths.formulas                       I  Selected remote version of com.google.android.gms.ads.dynamite, version >= 231710100
2023-06-10 20:53:21.488 22195-22195 System                  maths.formulas                       W  ClassLoader referenced unknown path: 
2023-06-10 20:53:21.489 22195-22195 nativeloader            maths.formulas                       D  Configuring classloader-namespace for other apk . target_sdk_version=33, uses_libraries=, library_path=/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/lib/arm64:/data/app/~~wZe3J7NoA9pT8CBTKiq5pw==/com.google.android.gms-tuTTSKXVm_J1gyKPoAibtw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.gms
2023-06-10 20:53:21.495 22195-22195 maths.formulas          maths.formulas                       W  ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk*1202183296:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes2.dex*3865217763:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes3.dex*3626936904:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes4.dex*831102210:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes5.dex*1115384458:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes6.dex*754051103:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes7.dex*14169318:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes8.dex*1770045591:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes9.dex*79722477:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes10.dex*668714246:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes11.dex*2360840502:/data/app/~~9ahLsxDMY7TNQPfTZmQ6XA==/maths.formulas-xQIL5cLUkwzcvU-0-tgNtg==/base.apk!classes12.dex*2041011401])
2023-06-10 20:53:21.500 22195-22195 DynamitePackage         maths.formulas                       D  Instantiated singleton DynamitePackage.
2023-06-10 20:53:21.500 22195-22195 DynamitePackage         maths.formulas                       D  Instantiating com.google.android.gms.ads.ChimeraAdOverlayCreatorImpl
2023-06-10 20:53:21.514 22195-22195 IS_CTS_MODE             maths.formulas                       D  false
2023-06-10 20:53:21.514 22195-22195 MULTI_WINDOW_ENABLED    maths.formulas                       D  false
2023-06-10 20:53:21.515 22195-22195 DecorView[]             maths.formulas                       D  getWindowModeFromSystem  windowmode is 1
2023-06-10 20:53:21.518 22195-22195 Compatibil...geReporter maths.formulas                       D  Compat change id reported: 210923482; UID 10710; state: ENABLED`

**Comment by ratson** [comment]
@merbin2012 The bug should have been fixed in `2.0.0-alpha.4`, let me know if it didn't.

**Comment by merbin2012** [comment]
@ratson Thanks for the fix, I'll check and let you know. Today Sunday so might little delay to check.

**Comment by ngdevr** [comment]
@ratson  I have a similar issue and had opened a discussion 10 days back.
https://github.com/admob-plus/admob-plus/discussions/581

I have just tried to get the latest version to test it. Unfortunately it still does not work. Banner works but none of the other ads open. They load but as soon as we try to show the ad, the whole app crashes. By the way I checked the latest version being fetched and it still is 2.0.0-alpha.3.

**Comment by merbin2012** [comment]
@ngdevr hi, two days back already published the 2.0.0-alpha.4 . Please check it in the following link https://www.npmjs.com/package/admob-plus-cordova/v/2.0.0-alpha.4

Note: I can't able to check the changes today due to sunday, I'll surely check tomorrow morning.

**Comment by ngdevr** [comment]
@merbin2012 my bad, fetching admob-plus-cordova was bringing 2.0.0-alpha.3 so I tried to fetch it by admob-plus-cordova@2.0.0-alpha.4 where I made a typo and hence, got error that this version does not exist in the registry. I am able to fetch 2.0.0-alpha.4 by using admob-plus-cordova@2.0.0-alpha.4 in the "cordova plugin add" command. One question, shouldn't it automatically fetch the latest version which is 2.0.0-alpha.4 in stead of 2.0.0-alpha.3?

Anyways, after fetching the specific 2.0.0-alpha.4, I tested banner, appopen and interstitial and these 3 are working.

**Comment by merbin2012** [comment]
@ngdevr  Uninstall and try with @latest

**Comment by merbin2012** [comment]
@ngdevr the version name is saved in package.json, so the specific version will install also if you reinstall the platforms

**Comment by ratson** [comment]
It was released under `next` tag because of waiting for https://github.com/admob-plus/admob-plus/pull/586
`2.0.0-alpha.5` is released with the `latest` tag.
Please try it out and let me know the result.

**Comment by merbin2012** [comment]
@ratson ooh, thanks.

**Comment by ngdevr** [comment]
@ratson @merbin2012 Update: Tried with @latest which is fetching 2.0.0-alpha.5. Banner, appopen and interstitial works.

**Comment by merbin2012** [comment]
@ratson This problem has been fixed. Thank you.
